package com.spacekey.algorithm.global;

/**
 * @author yxfang
 * @date 2016-8-3
 * All the global variables
 */
public class Config {
	//stem file paths
	public static String stemFile = "./stemmer.lowercase.txt";
	public static String stopFile = "./stopword.txt";
	
	//dataset
	public static String root = "C:\\Users\\WagJK\\Desktop\\FYP\\SpaceKey\\dataset\\";
	
	public static String rootUK = root + "UK\\";
	public static String locUK = rootUK + "loc";
	public static String docUK = rootUK + "doc";
	public static String patternUK = rootUK + "pattern";
	public static String indexUK = rootUK + "leaf\\";
	public static String invertUK = rootUK + "invert/";
	
	public static String rootNY = root + "NewYork\\";
	public static String locNY = rootNY + "loc";
	public static String docNY = rootNY + "doc";
	public static String patternNY = rootNY + "pattern";
	public static String indexNY = rootNY + "leaf\\";
	public static String invertNY = rootNY + "invert/";
	
	public static String rootLA = root + "dataLA\\";
	public static String locLA = rootLA + "loc";
	public static String docLA = rootLA + "doc";
	public static String patternLA = rootLA + "pattern";
	public static String indexLA = rootLA + "leaf/";
	public static String invertLA = rootLA + "invert/";
	
	public static String rootTW = root + "TW\\";
	public static String locTW = rootTW + "loc";
	public static String docTW = rootTW + "doc";
	public static String patternTW = rootTW + "pattern";
	public static String indexTW = rootTW + "leaf/";
	public static String invertTW = rootTW + "invert/";
	
	//log file
	public static String logFilePath = ".\\info\\log" + System.currentTimeMillis();
	
	//parameter of the IR-tree
	public static int Fanout = 100;
	
	//MPJ: the number of fold where foldname is generated by hashcode
	public static int foldNum = 1000;

	//parameter of selecting the anchors
	public static double alpha = 2.0;
	
	//Chernoff bound parameters
	public static double epsilon = 0.2;
	public static double delta = 0.2;
	public static double theta = 0.5;//stop sampling if there is not any qualified pair after sampling theta pairs
	
}
